title: Charley Sanchez
description: PhD student in Computer Science at UMBC, studying the security of foundation models for physiological signals.
url: https://charleysanchez.github.io
baseurl: ""
lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Charley Sanchez
  email: charleysanchez@umbc.edu

social:
  name: Charley Sanchez
  links:
    - https://github.com/charleysanchez
    - https://www.linkedin.com/in/charley-sanchez-034745297/

exclude:
  - README.md

defaults:
  - scope: {path: ""}
    values:
      layout: default
      image: /assets/img/charley-portrait.jpg
